# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.14.0.dev12+g5a29b6c.d20220128'
version_tuple = (0, 14, 0, 'dev12', 'g5a29b6c.d20220128')
